version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/database
    env_file: ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", $POSTGRES_USER]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      ENV: dev
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file: ./.env
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  database:
