version: '3.8'

services:
  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testtech
    healthcheck:
      test: ["CMD", "pg_isready", "-U", $POSTGRES_USER]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
  
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   env_file: ./.env
  #   expose:
  #     - 8080
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  database:
